"""Type stubs for sexpdata (S-expression parser)."""
from typing import Any

class String(str):
    @classmethod
    def quote(cls, string: str) -> str: ...
    @classmethod
    def unquote(cls, string: str) -> str: ...
    def value(self) -> str: ...

class Symbol(String):
    def value(self) -> str: ...

class Quoted(tuple[Any, ...]):
    x: Any
    def __new__(cls, x: Any) -> "Quoted": ...

def parse(string: str, **kwds: Any) -> list[Any]: ...
def loads(string: str, **kwds: Any) -> Any: ...
def dumps(obj: Any, **kwds: Any) -> str: ...
