"""Type stubs for sexpdata (S-expression parser)."""
from typing import TypeAlias

class String(str):
    @classmethod
    def quote(cls, string: str) -> str: ...
    @classmethod
    def unquote(cls, string: str) -> str: ...
    def value(self) -> str: ...

class Symbol(String):
    def value(self) -> str: ...

class Quoted(tuple["SexpNode", ...]):
    x: "SexpNode"
    def __new__(cls, x: "SexpNode") -> "Quoted": ...

SexpNode = str | int | float | Symbol | Quoted | list["SexpNode"]

def parse(string: str, **kwds: object) -> list[SexpNode]: ...
def loads(string: str, **kwds: object) -> SexpNode: ...
def dumps(obj: SexpNode, **kwds: object) -> str: ...
